language: node_js
node_js:
  - "node"

cache: yarn

before_deploy:
  - yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: gatsby
  local-dir: public
  target-branch: master
